services:
  agent-ssh:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JENKINS_AGENT_SSH_PUBKEY: ${JENKINS_AGENT_SSH_PUBKEY}
    #env_file: .env
    ports:
      - "${AGENT_SSH_PORT:-2222}:22"
    restart: unless-stopped
    #volumes:
      # Monte le socket Docker si tes jobs doivent faire docker build/run SUR L’AGENT
      #- /var/run/docker.sock:/var/run/docker.sock
    # Si "permission denied" sur le socket : renseigne DOCKER_GID et décommente :
    # user: "1000:${DOCKER_GID}"
