jenkins:
  systemMessage: "Jenkins as Code — provisionné via JCasC ✅"
  numExecutors: 0

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_ID:-admin}"
          password: "${JENKINS_ADMIN_PASSWORD:-changeMe!}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  location:
    url: "${JENKINS_URL:-http://localhost:8080/}"

credentials:
  system:
    domainCredentials:
      - credentials:
          # GitHub PAT (pour GitHub Branch Source)
          - string:
              id: "github-token"
              description: "GitHub PAT for branch indexing"
              scope: GLOBAL
              secret: "${GITHUB_PAT}"                 # ← passe via env
          # GitLab PAT (pour GitLab Branch Source)
          - string:
              id: "gitlab-token"
              description: "GitLab PAT for branch indexing"
              scope: GLOBAL
              secret: "${GITLAB_PAT}"

jobs:
  # Active la/les définitions Job DSL
  - file: /var/jenkins_home/casc_jobs/mbp_github.groovy
  # - file: /var/jenkins_home/casc_jobs/mbp_gitlab.groovy   # décommente si GitLab
